name: fuzzer

on:
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug
  CC: /usr/bin/clang
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev cmake clang

    - name: Build Fuzzing
      run: cd ${{github.workspace}} && ./build.sh build_fuzz

    - name: Run Fuzzer
      run: cd ${{github.workspace}} && ./build.sh run_fuzz
