name: Docker Release Image Create and Push To Docker HUB

on:
  push:
    tags:
      - 'v2'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: ./build.sh docker

    - name: Push Docker image
      run: |
        docker tag portsentry:unstable portsentry/portsentry:latest
        docker tag portsentry:unstable portsentry/portsentry:${{ github.ref_name }}
        docker push portsentry/portsentry:latest
        docker push portsentry/portsentry:${{ github.ref_name }}

