name: System Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pcap
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev nmap

    - name: Build
      run: ./build.sh debug

    - name: System Test
      run: |
        cd system_test
        sudo ./run_all_tests.sh
