name: Unit Tests

on:
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pcap
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev nmap

# Since debug builds have asserts, tests might not be accurate and/or fail
# in debug builds. release build should provide better results.
    - name: Build
      run: ./build.sh build_test

    - name: Run Unit Tests
      run: ./build.sh run_test
